version: '3'

services:
  locust-master:
    container_name: locust-master
    image: locustio/locust
    ports:
      - "9089:8089"
      - "5557:5557"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --master
    networks:
      - his-app-network
  locust-worker:
    image: locustio/locust
    deploy:
      replicas: 8
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    networks:
      - his-app-network

networks:
  his-app-network:
    driver: bridge
    name: his-app-network
